### ISSUE TITLE
Provide a way to use graphical front page application 

### ISSUE THREAD

**Issue by spbrogan** [microsoft/mu_tiano_platforms#135]
Q35 is a great reference platform for lots of features.  
In the past it showed our reference BIOS Menu from OemSamplePkg and now it shows our plain-text, serial console, remote friendly app from SetupCfg. 

We should provide an easy way to enable both/either as each have their use cases.

**Comment by kuqin12** [comment]
This seems like something @mikeytdisco was entertaining recently?
