### ISSUE TITLE
[Feature]: Enable Q35 to run without SMM

### ISSUE THREAD

**Issue by cfernald** [microsoft/mu_tiano_platforms#240]
### Feature Overview

Q35 currently requires SMM to execute, but this limits the ability to run under the Windows HVX acceleration. Q35 should be able to boot, fully functional, without SMM being supported by the machine. 

### Solution Overview

Create a build flag that will swap out the use of SMM and standalone MM for the DXE/runtime equivalents for flash access, etc. 

### Urgency

Medium

### Are you going to implement the feature request?

I will implement the feature

**Comment by makubacki** [comment]
@cfernald this can be closed now, right?

**Comment by cfernald** [comment]
Yep
