### ISSUE TITLE
[Bug]: release pipeline references old platform build templates

### ISSUE THREAD

**Issue by cfernald** [microsoft/mu_tiano_platforms#465]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

The release.yml references not existing templates.

### Expected Behavior

Release pipeline needs to use the new refactored build pipelines.

### Steps To Reproduce

N/A

### Build Environment

```markdown
- OS(s): ANY
- Tool Chain(s): NONE
- Targets Impacted: RELEASE
```

### Version Information

```text
N/A
```

### Urgency

High

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
I'll complete the PR for this - https://github.com/microsoft/mu_tiano_platforms/pull/459.
