### ISSUE TITLE
[Bug]: Run to Shell UefiCpuStackGuard Occasionally Hangs at TPL Assert

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_tiano_platforms#514]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

When running the "Run to Shell" step (notably on a CI server), the job occasionally hangs due to an assert. This causes the job to hang the pipeline run for at least an hour until the job timeout cancels the run.

Example of assert:

```
2023-04-24T21:22:04.4248215Z INFO - RecursionDynamic - 0x5D4
2023-04-24T21:22:04.4248723Z INFO - RecursionDynamic - 0x5FATAL ERROR - RaiseTpl with OldTpl(0x1E) > NewTpl(0x10)
2023-04-24T21:22:04.4253767Z INFO - ASSERT /__w/1/s/MU_BASECORE/MdeModulePkg/Core/Dxe/Event/Tpl.c(66): ((BOOLEAN)(0==1))
```

### Expected Behavior

The Run to Shell test should reliably run to shell if a change has not been made to impact stability of reaching EFI shell.

In any case, agents should not hang with no logic in place to detect the hang and resolve the issue.

### Steps To Reproduce

1. Build QemuQ35Pkg on Fedora 37 with the `GCC5` toolchain
2. Run "Run to Shell" step until the issue repros

### Build Environment

```markdown
Recent environment observed on:

- OS(s): Fedora 37
- Container Image: ghcr.io/tianocore/containers/fedora-37-test:54e5bd1
- Tool Chain(s): GCC5
- Architectures: IA32,X64
- Targets Impacted: DEBUG
```

### Version Information

```text
As of Commit: e0c6ef0d99db548675470cb2bfa0c8844181e302
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

Raw log file from PR gate that reproduced the issue attached - [RunToShellAssert.txt](https://github.com/microsoft/mu_tiano_platforms/files/11314929/RunToShellAssert.txt)

**Comment by TaylorBeebe** [comment]
Should be resolved when the following PR goes in: https://github.com/microsoft/mu_tiano_platforms/pull/531
